## 张量的创建与运算

In [1]:
import torch

torch.cuda.is_available()

True

### 张量（tensor）
#### 创建张量
##### 创建一维张量

In [8]:
x=torch.arange(12)                  # 序列填充
x=torch.tensor([1,3,5,7,9])         # 指定列表（List） 

##### 创建零一填充多维张量

In [9]:
torch.ones((2,3,4))
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

##### 创建正态分布随机数构成的张量

In [10]:
torch.randn(3,4)

tensor([[-1.3586,  1.4535, -0.0843, -2.1458],
        [ 0.4786, -1.0457, -0.2951,  0.4460],
        [ 0.4417,  1.0247, -0.1088,  0.2800]])

##### 创建与张量形状相同的全零张量

In [11]:
Z=torch.zeros_like(x)
Z

tensor([0, 0, 0, 0, 0])

##### 创建指定内容的多维张量

In [12]:
X=torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

##### 创建序列生成的多维张量
> 这里实际上生成了两张3×4的矩阵

In [21]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

#### 获取张量中元素总数

In [15]:
x.numel

<function Tensor.numel>

#### 重塑张量形状（创建矩阵）

In [17]:
y=torch.arange(12)                  # 序列填充
Y=y.reshape(3,4)
Y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

#### 获取张量形状

In [ ]:
X.shape
x.shape

torch.Size([3, 4])

#### -1自动计算维度
如果知道目标形状的宽度 or 高度，那么另一维度可以被自动计算出来。编码的时候哪一个参数直接写-1

In [ ]:
X=x.reshape(3,-1)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### 运算（operation）
#### 按标量进行加减乘除

In [ ]:
x=torch.tensor([1,2,4,8])
y=torch.tensor([2,2,2,2])

x+y
x-y
x*y
x/y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

#### 线代运算


##### 创建矩阵

In [20]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

##### 矩阵转置

In [19]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

##### 哈达玛积（Hadamard）
> 实际上是矩阵对应元素的乘法

In [22]:
A=torch.arange(9).reshape(3, 3)
B=torch.arange(9).reshape(3, 3)
A*B

tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])

##### 点积(内积)
> 点积在很多场合都有用。例如将两个向量规范化得到单位长度后，点积表示它们夹角的余弦。

我们可以通过先算哈达玛积再求和，也可以直接采用 `dot()` 函数

In [4]:
a=torch.arange(3)
b=torch.arange(3)
torch.sum(a*b)
torch.dot(a,b)

tensor(5)

 ##### 矩阵——向量积 mv

In [11]:
y=torch.arange(12)                  # 创建矩阵
Y=y.reshape(3,4)

x=torch.arange(4)                   # 创建向量 

torch.mv(Y,x)                       # 矩阵乘法须遵循：矩阵的列数与向量的行数一致 


tensor([14, 38, 62])

##### 矩阵——矩阵积 mm

In [13]:
X=y.reshape(4,3)
torch.mm(Y,X)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])

##### 标量与张量的加法与乘法

In [24]:
10+A
10*A

tensor([[ 0, 10, 20],
        [30, 40, 50],
        [60, 70, 80]])

##### 张量沿着某维度连结
* 维度0：**通常表示样本或数据点的数量**。在深度学习中，这个维度通常用于表示训练样本的数量或批处理大小。
* 维度1：**通常表示特征的数量**。在图像处理中，这个维度可能代表图像的宽度，而在自然语言处理中，它可能代表文本序列的长度

###### 沿着维度0连结

In [ ]:
X=torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
Y=torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

torch.cat((X,Y),dim=0)

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

###### 沿着维度1连结

In [ ]:
torch.cat((X,Y),dim=1)

tensor([[1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4]])

##### 求和降维
###### 沿所有轴降维

In [25]:
X.sum()

tensor(276)

###### 沿指定轴求和降维

In [32]:
A_sum_axis0 = A.sum(axis=0)  # 压缩0轴，就是把0轴的所有样本，累加到一起。最终剩下1轴（特征）
A_sum_axis0

A_sum_axis1 = A.sum(axis=1)  # 压缩1轴，就是把1轴的所有特征，累加到一起。最终剩下0轴（样本）
A_sum_axis1.shape

torch.Size([3])

##### 非降维求和

可以看到降维求和后，形状变成一维；非降维求和后，形状仍保持二维

In [31]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A.shape

torch.Size([3, 1])

#### 广播机制
> 广播机制实际上解决的问题是：如何计算两个形状不同的张量，如何$3×1$的矩阵如何与$1×2$的矩阵计算

#### 切片与索引
##### 用 -1 访问最后一个元素

In [ ]:
x=torch.tensor([1,3,5,7,9])         # 指定列表（List） 
x[-1]

tensor(9)

##### 指定某几行

In [ ]:
X=torch.tensor([[1,2,3,4],
                [1,2,3,5],
                [1,2,3,6],
                [1,2,3,7]])
X[0:2,:]

tensor([[1, 2, 3, 4],
        [1, 2, 3, 5]])